// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_chekmate/test/features/profile/domain/usecases/update_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_chekmate/features/profile/domain/entities/profile_entity.dart'
    as _i2;
import 'package:flutter_chekmate/features/profile/domain/entities/voice_prompt_entity.dart'
    as _i6;
import 'package:flutter_chekmate/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileStats_0 extends _i1.SmartFake implements _i2.ProfileStats {
  _FakeProfileStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileEntity?> getProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue: _i4.Future<_i2.ProfileEntity?>.value(),
      ) as _i4.Future<_i2.ProfileEntity?>);

  @override
  _i4.Future<_i2.ProfileEntity?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.ProfileEntity?>.value(),
      ) as _i4.Future<_i2.ProfileEntity?>);

  @override
  _i4.Future<void> updateProfile(_i2.ProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfileField(
    String? userId,
    String? field,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfileField,
          [
            userId,
            field,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> uploadAvatar(
    String? userId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            userId,
            filePath,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              userId,
              filePath,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> uploadCoverPhoto(
    String? userId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadCoverPhoto,
          [
            userId,
            filePath,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadCoverPhoto,
            [
              userId,
              filePath,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> uploadVideoIntro(
    String? userId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadVideoIntro,
          [
            userId,
            filePath,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadVideoIntro,
            [
              userId,
              filePath,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> addVoicePrompt(
    String? userId,
    _i6.VoicePromptEntity? voicePrompt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVoicePrompt,
          [
            userId,
            voicePrompt,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteVoicePrompt(
    String? userId,
    String? promptId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoicePrompt,
          [
            userId,
            promptId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> followUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isFollowing(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isFollowing,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.ProfileEntity>> getFollowers(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.ProfileEntity>>.value(<_i2.ProfileEntity>[]),
      ) as _i4.Future<List<_i2.ProfileEntity>>);

  @override
  _i4.Future<List<_i2.ProfileEntity>> getFollowing(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.ProfileEntity>>.value(<_i2.ProfileEntity>[]),
      ) as _i4.Future<List<_i2.ProfileEntity>>);

  @override
  _i4.Future<_i2.ProfileStats> getProfileStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileStats,
          [userId],
        ),
        returnValue: _i4.Future<_i2.ProfileStats>.value(_FakeProfileStats_0(
          this,
          Invocation.method(
            #getProfileStats,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.ProfileStats>);

  @override
  _i4.Future<List<_i2.ProfileEntity>> searchProfiles(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProfiles,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i2.ProfileEntity>>.value(<_i2.ProfileEntity>[]),
      ) as _i4.Future<List<_i2.ProfileEntity>>);

  @override
  _i4.Future<List<_i2.ProfileEntity>> getSuggestedProfiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedProfiles,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.ProfileEntity>>.value(<_i2.ProfileEntity>[]),
      ) as _i4.Future<List<_i2.ProfileEntity>>);

  @override
  _i4.Future<void> blockUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportUser(
    String? userId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportUser,
          [
            userId,
            reason,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
