// File generated by FlutterFire CLI.
// Firebase configuration for ChekMate app
// Last updated: October 22, 2025

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZKl4d1Mc4n1-j6IrTOs1_1UYAa3K9z0',
    appId: '1:209000668199:web:d818c18765f064a41ac202',
    messagingSenderId: '209000668199',
    projectId: 'chekmate-a0423',
    authDomain: 'chekmate-a0423.firebaseapp.com',
    storageBucket: 'chekmate-a0423.firebasestorage.app',
    measurementId: 'G-68YF9Z1RNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiOPIoXj59reeRJ5c5amUufrDHDa_aN-g',
    appId: '1:209000668199:android:efedf1faf8f908721ac202',
    messagingSenderId: '209000668199',
    projectId: 'chekmate-a0423',
    storageBucket: 'chekmate-a0423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ1KQOw3dXeRGOhZVcpN6MgPs9OZYp5jc',
    appId: '1:209000668199:ios:c6c7680afe597e441ac202',
    messagingSenderId: '209000668199',
    projectId: 'chekmate-a0423',
    storageBucket: 'chekmate-a0423.firebasestorage.app',
    iosBundleId: 'com.chekmate.app',
    iosClientId:
        '209000668199-ecoboha2cfiui0325p5l74pqbdpc0mgd.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.chekmate.app',
  );
}

// DEPLOYMENT NOTE: Replace this file by running:
// 1. dart pub global activate flutterfire_cli
// 2. flutterfire configure
// 3. Follow the prompts to connect to your Firebase project
//
// This file contains placeholder values for development.
// For production deployment, you must configure with real Firebase project credentials.
